name: CreateRelease

on:
  push:
    branches:
    - master

jobs:

  publishReleaseJob:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -p artifact
    - run: |
        curl -sS https://api.github.com/repos/pCYSl5EDgo/UniNativeLinq-Core/releases | jq ".[0] | .tag_name" | awk '{print substr($0, 2, length($0)-2)}' > version
        cat version

    - run: |
        printf "{\"tag_name\":\"%s\"}" $(cat version) > json
        cat json
        curl -sS -X POST -H 'content-type:application/json' -d @"json" https://api.github.com/repos/pCYSl5EDgo/UniNativeLinq-Core/releases > response
        cat response
        cat response | jq '.upload_url' > upload_url
    - run: |
        cat upload_url
        #curl -sS -X POST -H 'content-type:application/json' -d $JSON $(cat upload_url)
