name: CreateRelease

on:
  push:
    branches:
    - master

jobs:
  buildReleaseJob:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag: [2018.4.9f1]

    steps:
    - uses: actions/checkout@master
    - run: mkdir -p artifact
    - uses: actions/setup-dotnet@v1.0.2
      with:
        dotnet-version: '3.0.100'
    - run: |
        cd UniNativeLinq
        dotnet build -c Release
    - run: |
        cd CecilRewrite
        dotnet run "/opt/Unity/Editor/Data/Managed/UnityEngine/" "../UniNativeLinq/bin/Release/netstandard2.0/UniNativeLinq.dll" "../artifact/UniNativeLinq.bytes"
    - run: mkdir -p ~/.ssh
    - run: echo $netrc > ~/.netrc
      env:
        netrc: ${{ secrets.netrc }}
    - run: git clone https://github.com/pCYSl5EDgo/UniNativeLinq-EditorExtension-Test.git
    - run: cp -f artifact/UniNativeLinq.bytes "UniNativeLinq-EditorExtension-Test/Assets/Plugins/UNL/DLLs/UniNativeLinq.bytes"
    - run: |
        cd UniNativeLinq-EditorExtension-Test
        git config --global user.email "pcysl5edgo@yahoo.co.jp"
        git config --global user.name "pCYSl5EDgo"
        git commit -a -m "[update]DLL Update of $GITHUB_SHA"
        git push -v
    - uses: actions/upload-artifact@master
      with:
        name: bytes
        path: artifact