name: CreateRelease

on:
  push:
    branches:
    - master

jobs:
  buildReleaseJob:
    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}
    strategy:
      matrix:
        unity-tag: [2018.4.9f1]

    steps:
    - uses: actions/checkout@master
    - run: mkdir -p artifact
    - uses: actions/setup-dotnet@v1.0.2
      with:
        dotnet-version: '3.0.100'
    - run: |
        cd UniNativeLinq
        dotnet build -c Release
    - run: |
        cd CecilRewrite
        dotnet run "/opt/Unity/Editor/Data/Managed/UnityEngine/" "../UniNativeLinq/bin/Release/netstandard2.0/UniNativeLinq.dll" "../artifact/UniNativeLinq.bytes"
    - uses: actions/upload-artifact@master
      with:
        name: bytes
        path: artifact

  pushGitJob:
    runs-on: ubuntu-latest
    needs: buildReleaseJob
    steps:
    - run: mkdir -p artifact
    - uses: actions/download-artifact@master
      with:
        name: bytes
        path: artifact
    - run: echo $NETRC > .netrc
      env:
        NETRC: ${{ secrets.netrc }}
    - run: git clone https://github.com/pCYSl5EDgo/UniNativeLinq-EditorExtension
    - run: cp -f artifact/UniNativeLinq.bytes "UniNativeLinq-EditorExtension/Editor/DLLs/UniNativeLinq.bytes"
    - name: git commit
      run: |
        cd UniNativeLinq-EditorExtension
        git commit -a -m "[update]DLL Update of $GITHUB_SHA"
    - name: git push
      run: |
        cd UniNativeLinq-EditorExtension
        git push

  publishReleaseJob:
    runs-on: ubuntu-latest
    needs: buildReleaseJob
    steps:
    - run: mkdir -p artifact
    - uses: actions/download-artifact@master
      with:
        name: bytes
        path: artifact
    - run: curl -sS https://api.github.com/repos/pCYSl5EDgo/UniNativeLinq-Core/releases | jq ".[0] | .tag_name" |  awk '{$0=substr($0, 1, length($0)-2);split($0,versions,".");print versions[1] "." versions[2] "." (versions[3]+1)}' > next_version
    - run: |
        NEXTVERSION=$(cat next_version)
        JSON=$(printf "{\"tag_name\":\"%s\",\"target_commitish\":\"master\",\"name\":\"自動化されたリリース：%s\",\"body\":\"このリリースは自動化されたものです。\"}" NEXT_VERSION NEXT_VERSION)
        cat $JSON
        echo "\n"
        curl -sS -X POST -H 'content-type:application/json' --data-urlencode $JSON https://api.github.com/repos/pCYSl5EDgo/UniNativeLinq-Core/releases > response
        echo "\n"
        cat response
        echo "\n"
        cat response | jq '.upload_url' > upload_url
    - run: cat upload_url
        #curl -sS -X POST -H 'content-type:application/json' --data-urlencode $JSON $(cat upload_url)
